### PR TITLE
Full revision of Entities & json support

### PR DESCRIPTION
**Pull request by st0o0**

### CODE REVIEW

**Comment by LineOfC0d3** [comment]
Looks good 👍

There is a great degree of redundancy in the entities
i.e. the following Properties (found in many "xxPhoto" Entities)

`[JsonProperty("ispublic")]`
`public bool IsPublic { get; set; }`

`[JsonProperty("isfriend")]`
`public bool IsFriend { get; set; }`

`[JsonProperty("isfamily")]`
`public bool IsFamily { get; set; }`

**Comment by st0o0** [comment]
@LineOfC0d3 
yes, agree with you. What would be a naming suggestion for this 

Entity

**Comment by LineOfC0d3** [comment]
@st0o0 
I think something like "Social Circles" or "Visibility Group" could be a suitable name for these three properties.

**Review by LineOfC0d3 — APPROVED** [review]
Amazing naming scheme 👍

**Pull request merged**
